name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # clona/actualiza solo

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Reiniciar con PM2
        run: pm2 restart snippets-test || pm2 start "npx serve dist -p 3052" --name "snippets-test" && pm2 save
