name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test control servicio
        run: |
          Write-Host "Antes:"
          Get-Service snippets-test

          try {
            Stop-Service snippets-test -Force
            Write-Host "Stop OK"
          }
          catch {
            Write-Host "Stop ERROR:"
            Write-Host $_
          }

          Start-Sleep -Seconds 5

          try {
            Start-Service snippets-test
            Write-Host "Start OK"
          }
          catch {
            Write-Host "Start ERROR:"
            Write-Host $_
          }

          Write-Host "Despues:"
          Get-Service snippets-test

      # - name: Reiniciar app
      #   run: |
      #     Stop-Service -Name "snippets-test" -Force -ErrorAction SilentlyContinue
      #     Start-Service -Name "snippets-test"
